# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TripPlanner-Google' do
  pod 'GoogleMaps'
  pod 'SwiftyJSON'
  pod 'Gloss'
end

target 'TripPlanner-GoogleTests' do

end

target 'TripPlanner-GoogleUITests' do

end
